In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv(r'C:\Users\amraw\Downloads\assurances_clients.csv')

In [21]:
# 1. Audit du dataset

In [22]:
print(df.shape)

(608, 12)

In [23]:
print(df.dtypes)

id_client              object
civilite               object
age                   float64
region                 object
type_contrat           object
date_souscription      object
prime_annuelle        float64
nb_sinistres            int64
montant_sinistres     float64
statut                 object
conseiller             object
score_satisfaction    float64
dtype: object

In [24]:
df.head(10)

,id_client,civilite,age,region,type_contrat,date_souscription,prime_annuelle,nb_sinistres,montant_sinistres,statut,conseiller,score_satisfaction
0,CLI0001,M.,62.0,Île-de-France,Auto,2019-01-01,1674.55,2,7371.27,Actif,Moreau,NaN
1,CLI0002,Mme,49.0,Occitanie,Vie,2019-01-04,889.00,4,7836.66,Résilié,Bernard,6.0
2,CLI0003,M.,69.0,PACA,Prévoyance,2019-01-08,NaN,2,8440.68,Actif,Martin,8.0
3,CLI0004,M.,47.0,Occitanie,Auto,2019-01-11,1304.22,2,6618.36,Actif,Martin,3.0
4,CLI0005,M.,64.0,Auvergne,Prévoyance,2019-01-15,1738.36,1,9086.33,Actif,Bernard,1.0
5,CLI0006,Mme,52.0,Île-de-France,Habitation,2019-01-19,2291.25,2,13781.02,Actif,Bernard,3.0
6,CLI0007,M.,72.0,Île-de-France,Auto,2019-01-22,2203.37,5,5434.02,Actif,Bernard,3.0
7,CLI0008,M.,57.0,Normandie,Prévoyance,2019-01-26,1659.46,0,0.00,Actif,Martin,5.0
8,CLI0009,M.,69.0,Auvergne,Habitation,2019-01-30,2502.70,3,13416.79,Actif,Moreau,4.0
9,CLI0010,Mme,33.0,Île-de-France,Vie,2019-02-02,1406.41,0,0.00,Actif,Bernard,4.0

In [25]:
print(df.isnull().sum())

id_client              0
civilite               0
age                   10
region                 0
type_contrat           0
date_souscription      0
prime_annuelle        25
nb_sinistres           0
montant_sinistres      0
statut                 0
conseiller            16
score_satisfaction    20
dtype: int64

In [26]:
print(df.duplicated().sum())

8

In [27]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
603     True
604     True
605     True
606     True
607     True
Length: 608, dtype: bool

In [28]:
df['type_contrat'].unique()

array(['Auto', 'Vie', 'Prévoyance', 'Habitation', 'Santé'], dtype=object)

In [29]:
df['statut'].unique()

array(['Actif', 'Résilié', 'Suspendu'], dtype=object)

In [30]:
df.describe()

,age,prime_annuelle,nb_sinistres,montant_sinistres,score_satisfaction
count,598.000000,583.000000,608.000000,608.000000,588.000000
mean,46.488294,1567.370377,2.565789,6266.882303,5.647959
std,16.492190,791.136342,1.684980,4867.259540,2.816394
min,18.000000,200.930000,0.000000,0.000000,1.000000
25%,33.000000,845.505000,1.000000,1376.280000,3.000000
50%,46.000000,1567.500000,3.000000,6234.345000,6.000000
75%,62.000000,2261.760000,4.000000,10601.512500,8.000000
max,74.000000,2987.350000,5.000000,14991.990000,10.000000

In [31]:
# 2. Nettoyage du dataset

In [32]:
# 2.1 Suppression des doublons

In [33]:
df_no_double = df.drop_duplicates()
print(df_no_double)

    id_client civilite   age         region type_contrat date_souscription  \
0     CLI0001       M.  62.0  Île-de-France         Auto        2019-01-01
1     CLI0002      Mme  49.0      Occitanie          Vie        2019-01-04
2     CLI0003       M.  69.0           PACA   Prévoyance        2019-01-08
3     CLI0004       M.  47.0      Occitanie         Auto        2019-01-11
4     CLI0005       M.  64.0       Auvergne   Prévoyance        2019-01-15
..        ...      ...   ...            ...          ...               ...
595   CLI0596      Mme  54.0       Bretagne   Habitation        2024-12-16
596   CLI0597       M.   NaN      Normandie         Auto        2024-12-20
597   CLI0598       M.  27.0       Bretagne          Vie        2024-12-23
598   CLI0599      Mme  56.0           PACA   Prévoyance        2024-12-27
599   CLI0600      Mme  74.0       Auvergne   Habitation        2024-12-31

     prime_annuelle  nb_sinistres  montant_sinistres   statut conseiller  \
0           1674.55             2            7371.27    Actif     Moreau
1            889.00             4            7836.66  Résilié    Bernard
2               NaN             2            8440.68    Actif     Martin
3           1304.22             2            6618.36    Actif     Martin
4           1738.36             1            9086.33    Actif    Bernard
..              ...           ...                ...      ...        ...
595         2711.48             3            5603.32  Résilié     Moreau
596         1656.53             3             757.33  Résilié        NaN
597         1453.29             3            9412.30  Résilié     Martin
598         1761.90             5            5784.20    Actif     Dubois
599          664.90             1           14044.01    Actif     Moreau

     score_satisfaction
0                   NaN
1                   6.0
2                   8.0
3                   3.0
4                   1.0
..                  ...
595                 4.0
596                 5.0
597                 9.0
598                 1.0
599                 3.0

[600 rows x 12 columns]

In [34]:
# 2.2 Mise à jour du dataframe

In [35]:
df_clean = df.copy()

In [36]:
# 2.3 Remplacement des valeurs sur prime annuelle en 2 formules

In [37]:
df_clean['prime_annuelle'] = df['prime_annuelle'].fillna (df['prime_annuelle'].median())
print(df_clean['prime_annuelle'])

0      1674.55
1       889.00
2      1567.50
3      1304.22
4      1738.36
        ...
603    1930.54
604     743.07
605    1992.47
606    2583.29
607    1285.49
Name: prime_annuelle, Length: 608, dtype: float64

In [38]:
df_clean['prime_annuelle'] = df.groupby('type_contrat')['prime_annuelle'].transform(lambda x: x.fillna(x.median()))
print(df_clean['prime_annuelle'])

0      1674.55
1       889.00
2      1724.56
3      1304.22
4      1738.36
        ...
603    1930.54
604     743.07
605    1992.47
606    2583.29
607    1285.49
Name: prime_annuelle, Length: 608, dtype: float64

In [39]:
# 2.4 Remplacement des valeurs sur scrore satisfaction en 2 formules

In [40]:
df_clean['score_satisfaction'] = df_clean['score_satisfaction'].fillna(df_clean['score_satisfaction'].mean())
print(df_clean['score_satisfaction'])

0       5.647959
1       6.000000
2       8.000000
3       3.000000
4       1.000000
         ...
603     6.000000
604     5.000000
605     7.000000
606    10.000000
607     2.000000
Name: score_satisfaction, Length: 608, dtype: float64

In [41]:
df_clean['score_satisfaction'] = df.groupby('conseiller')['score_satisfaction'].transform(lambda x: x.fillna(x.mean()))
print(df_clean['score_satisfaction'])

0       5.713043
1       6.000000
2       8.000000
3       3.000000
4       1.000000
         ...
603     6.000000
604          NaN
605     7.000000
606    10.000000
607     2.000000
Name: score_satisfaction, Length: 608, dtype: float64

In [42]:
# 2.5 Remplacement des valeurs sur conseiller

In [43]:
df_clean['conseiller'] = df_clean['conseiller'].fillna('Non assigné')
print(df_clean['conseiller'])

0           Moreau
1          Bernard
2           Martin
3           Martin
4          Bernard
          ...
603        Bernard
604    Non assigné
605        Bernard
606          Leroy
607          Leroy
Name: conseiller, Length: 608, dtype: object

In [44]:
#2.6 Remplacement des valeurs sur age

In [45]:
df_clean['age'] = df_clean['age'].fillna(df_clean['age'].median())
print(df_clean['age'])

0      62.0
1      49.0
2      69.0
3      47.0
4      64.0
       ...
603    52.0
604    39.0
605    67.0
606    66.0
607    68.0
Name: age, Length: 608, dtype: float64

In [46]:
#2.7 Création de la colonne année de souscription

In [47]:
import pandas as pd

df_clean['date_souscription'] = pd.to_datetime(df_clean['date_souscription'])

In [48]:
df_clean['année_souscription'] = df_clean['date_souscription'].dt.year
print(df_clean['année_souscription'])

0      2019
1      2019
2      2019
3      2019
4      2019
       ...
603    2021
604    2022
605    2020
606    2019
607    2023
Name: année_souscription, Length: 608, dtype: int32

In [49]:
#2.8 Création de la colonne mois de souscription

In [50]:
df_clean['mois_souscription'] = df_clean['date_souscription'].dt.month_name()
print(df_clean['mois_souscription'])

0       January
1       January
2       January
3       January
4       January
         ...
603       March
604    November
605     January
606      August
607       March
Name: mois_souscription, Length: 608, dtype: object

In [51]:
#2.9 Création de la colonne anciènneté en jour

In [52]:
df_clean['ancienneté_jours'] = (pd.Timestamp.today() - df_clean['date_souscription']).dt.days
print(df_clean['ancienneté_jours'])

0      2715
1      2712
2      2708
3      2705
4      2701
       ...
603    1911
604    1307
605    2339
606    2500
607    1183
Name: ancienneté_jours, Length: 608, dtype: int64

In [53]:
import pandas as pd

print(pd.Timestamp.today())

2026-06-08 18:50:56.615008

In [54]:
#2.10 Vérification des manquants

In [55]:
print(df_clean.isnull().sum())

id_client              0
civilite               0
age                    0
region                 0
type_contrat           0
date_souscription      0
prime_annuelle         0
nb_sinistres           0
montant_sinistres      0
statut                 0
conseiller             0
score_satisfaction    16
année_souscription     0
mois_souscription      0
ancienneté_jours       0
dtype: int64

In [56]:
#3 Analyse des sinistralités

In [57]:
#3.1 Contrat avec le plus fort taux de sinistralité

In [58]:
df_clean.groupby('type_contrat')[['nb_sinistres','montant_sinistres']].sum().sort_values('montant_sinistres',ascending=False).head(1)

              nb_sinistres  montant_sinistres
type_contrat
Prévoyance             349          877251.15

In [59]:
df_clean['taux_sinistralite'] = (df_clean['montant_sinistres'] / df_clean['nb_sinistres'])
print(df_clean['taux_sinistralite'])

0      3685.635000
1      1959.165000
2      4220.340000
3      3309.180000
4      9086.330000
          ...
603    2563.530000
604    6173.705000
605    4224.665000
606     122.493333
607      37.840000
Name: taux_sinistralite, Length: 608, dtype: float64

In [60]:
#3.2 Région génèrant le plus de sinistres en volume total

In [61]:
df_clean.groupby('region')[['nb_sinistres']].sum().sort_values('nb_sinistres',ascending=False).head(1)

           nb_sinistres
region
Occitanie           282

In [62]:
#3.3 Crééer une colonne 'Ratio_sinistres'

In [63]:
df_clean['Ratio_sinistres'] = (df_clean['montant_sinistres'] / df_clean['prime_annuelle'])
print(df_clean['Ratio_sinistres'])

0       4.401941
1       8.815141
2       4.894396
3       5.074573
4       5.226955
         ...
603     2.655765
604    16.616752
605     4.240631
606     0.142253
607     0.117745
Name: Ratio_sinistres, Length: 608, dtype: float64

In [64]:
df_clean.head(10)

,id_client,civilite,age,region,type_contrat,date_souscription,prime_annuelle,nb_sinistres,montant_sinistres,statut,conseiller,score_satisfaction,année_souscription,mois_souscription,ancienneté_jours,taux_sinistralite,Ratio_sinistres
0,CLI0001,M.,62.0,Île-de-France,Auto,2019-01-01,1674.55,2,7371.27,Actif,Moreau,5.713043,2019,January,2715,3685.635000,4.401941
1,CLI0002,Mme,49.0,Occitanie,Vie,2019-01-04,889.00,4,7836.66,Résilié,Bernard,6.000000,2019,January,2712,1959.165000,8.815141
2,CLI0003,M.,69.0,PACA,Prévoyance,2019-01-08,1724.56,2,8440.68,Actif,Martin,8.000000,2019,January,2708,4220.340000,4.894396
3,CLI0004,M.,47.0,Occitanie,Auto,2019-01-11,1304.22,2,6618.36,Actif,Martin,3.000000,2019,January,2705,3309.180000,5.074573
4,CLI0005,M.,64.0,Auvergne,Prévoyance,2019-01-15,1738.36,1,9086.33,Actif,Bernard,1.000000,2019,January,2701,9086.330000,5.226955
5,CLI0006,Mme,52.0,Île-de-France,Habitation,2019-01-19,2291.25,2,13781.02,Actif,Bernard,3.000000,2019,January,2697,6890.510000,6.014630
6,CLI0007,M.,72.0,Île-de-France,Auto,2019-01-22,2203.37,5,5434.02,Actif,Bernard,3.000000,2019,January,2694,1086.804000,2.466231
7,CLI0008,M.,57.0,Normandie,Prévoyance,2019-01-26,1659.46,0,0.00,Actif,Martin,5.000000,2019,January,2690,NaN,0.000000
8,CLI0009,M.,69.0,Auvergne,Habitation,2019-01-30,2502.70,3,13416.79,Actif,Moreau,4.000000,2019,January,2686,4472.263333,5.360926
9,CLI0010,Mme,33.0,Île-de-France,Vie,2019-02-02,1406.41,0,0.00,Actif,Bernard,4.000000,2019,February,2683,NaN,0.000000

In [65]:
#3.4 Déterminer le nombre de clients au ratio supérieur à 1

In [66]:
df_clean_client_ratio_sup_1 = (df_clean['Ratio_sinistres'] > 1).sum()
print (df_clean_client_ratio_sup_1)

454

In [67]:
#3.5 Déterminer le pourcentage que vaut le nombre de clients au ratio supérieur à 1

In [68]:
df_clean_client_ratio_sup_1 = (df_clean['Ratio_sinistres'] > 1).mean()*100
print (df_clean_client_ratio_sup_1)

74.67105263157895

In [69]:
#3.6 Déterminer les clients au ratio supérieur à 1

In [70]:
df_clean_ratio_sup_1 = df_clean[df_clean['Ratio_sinistres'] > 1]
print(df_clean_ratio_sup_1)

    id_client civilite   age         region type_contrat date_souscription  \
0     CLI0001       M.  62.0  Île-de-France         Auto        2019-01-01
1     CLI0002      Mme  49.0      Occitanie          Vie        2019-01-04
2     CLI0003       M.  69.0           PACA   Prévoyance        2019-01-08
3     CLI0004       M.  47.0      Occitanie         Auto        2019-01-11
4     CLI0005       M.  64.0       Auvergne   Prévoyance        2019-01-15
..        ...      ...   ...            ...          ...               ...
600   CLI0523      Mme  67.0  Île-de-France   Habitation        2024-03-24
602   CLI0304      Mme  53.0           PACA        Santé        2022-01-13
603   CLI0221       M.  52.0      Occitanie   Habitation        2021-03-15
604   CLI0386      Mme  39.0      Normandie         Auto        2022-11-09
605   CLI0104      Mme  67.0           PACA        Santé        2020-01-12

     prime_annuelle  nb_sinistres  montant_sinistres   statut   conseiller  \
0           1674.55             2            7371.27    Actif       Moreau
1            889.00             4            7836.66  Résilié      Bernard
2           1724.56             2            8440.68    Actif       Martin
3           1304.22             2            6618.36    Actif       Martin
4           1738.36             1            9086.33    Actif      Bernard
..              ...           ...                ...      ...          ...
600         2942.74             4            5860.23  Résilié       Moreau
602         1353.97             4            3286.76    Actif       Martin
603         1930.54             2            5127.06    Actif      Bernard
604          743.07             2           12347.41    Actif  Non assigné
605         1992.47             2            8449.33  Résilié      Bernard

     score_satisfaction  année_souscription mois_souscription  \
0              5.713043                2019           January
1              6.000000                2019           January
2              8.000000                2019           January
3              3.000000                2019           January
4              1.000000                2019           January
..                  ...                 ...               ...
600            9.000000                2024             March
602            2.000000                2022           January
603            6.000000                2021             March
604                 NaN                2022          November
605            7.000000                2020           January

     ancienneté_jours  taux_sinistralite  Ratio_sinistres
0                2715          3685.6350         4.401941
1                2712          1959.1650         8.815141
2                2708          4220.3400         4.894396
3                2705          3309.1800         5.074573
4                2701          9086.3300         5.226955
..                ...                ...              ...
600               806          1465.0575         1.991420
602              1607           821.6900         2.427498
603              1911          2563.5300         2.655765
604              1307          6173.7050        16.616752
605              2339          4224.6650         4.240631

[454 rows x 17 columns]

In [71]:
#3.7 Les types de contrat dans les ratios supérieurs à 1

In [72]:
df_clean_ratio_sup_1['type_contrat'].value_counts()

type_contrat
Prévoyance    98
Habitation    95
Auto          90
Santé         87
Vie           84
Name: count, dtype: int64

In [73]:
#3.8 Le type de contrat le plus dominant

In [74]:
df_clean_ratio_sup_1['type_contrat'].value_counts().idxmax()

'Prévoyance'

In [75]:
#3.9 Clients ayant payés plus de 1000 euros de prime

In [76]:
df_clean_client_sur_moyenne = df_clean.loc[df_clean['prime_annuelle'] > 1000,'id_client']
print (df_clean_client_sur_moyenne)

0      CLI0001
2      CLI0003
3      CLI0004
4      CLI0005
5      CLI0006
        ...
602    CLI0304
603    CLI0221
605    CLI0104
606    CLI0060
607    CLI0420
Name: id_client, Length: 427, dtype: object

In [77]:
#4 Performances des conseillers

In [78]:
#4.1 Tableau recapitulatif par conseiller

In [79]:
df_clean_perf_conseillers = df_clean.groupby('conseiller').agg ( Nb_contrats = ('type_contrat', 'count'),Prime_moy = ('prime_annuelle', 'mean') , Score_satisfaction = ('score_satisfaction', 'mean'),Nb_sinistres = ('nb_sinistres', 'sum'),
).round(2)
print(df_clean_perf_conseillers)

             Nb_contrats  Prime_moy  Score_satisfaction  Nb_sinistres
conseiller
Bernard              118    1698.46                5.48           283
Dubois               124    1514.36                5.43           316
Leroy                126    1602.61                5.87           341
Martin               105    1527.69                5.63           250
Moreau               119    1552.29                5.71           323
Non assigné           16    1198.77                 NaN            47

In [80]:
#4.2 Taux de résiliation

In [81]:
taux_resil = df_clean.groupby('conseiller')['statut'].apply( lambda x :round ((x == 'Résilié').sum() / len(x) * 100,1) ).rename('Taux_resiliation_%')
print(taux_resil)

conseiller
Bernard        22.0
Dubois         18.5
Leroy          25.4
Martin         28.6
Moreau         24.4
Non assigné    31.2
Name: Taux_resiliation_%, dtype: float64

In [ ]:
#4.3 Récap conseiller

In [91]:
recap_conseiller = df_clean.groupby('conseiller').agg (prime_totale = ('prime_annuelle','sum'),chiffre_affaire = ('montant_sinistres','sum'),score_satisfaction = ('score_satisfaction','sum'),).round(2)
print(recap_conseiller)

             prime_totale  chiffre_affaire  score_satisfaction
conseiller
Bernard         200418.86        747062.41              646.97
Dubois          187780.16        787694.19              673.73
Leroy           201929.26        743010.04              739.48
Martin          160407.83        591942.79              590.76
Moreau          184723.06        820405.37              679.85
Non assigné      19180.25        120149.64                0.00

In [ ]:
#4.4 Unir le tableau recapitulatif et le taux de résiliation

In [94]:
df_clean_perf_conseillers = df_clean_perf_conseillers.join(taux_resil)
print(df_clean_perf_conseillers)

             Nb_contrats  Prime_moy  Score_satisfaction  Nb_sinistres  \
conseiller
Bernard              118    1698.46                5.48           283
Dubois               124    1514.36                5.43           316
Leroy                126    1602.61                5.87           341
Martin               105    1527.69                5.63           250
Moreau               119    1552.29                5.71           323
Non assigné           16    1198.77                 NaN            47

             Taux_resiliation_%
conseiller
Bernard                    22.0
Dubois                     18.5
Leroy                      25.4
Martin                     28.6
Moreau                     24.4
Non assigné                31.2

In [ ]:
#4.5 Trie par score de satisfaction décroissant

In [97]:
df_clean_perf_conseillers = df_clean_perf_conseillers.sort_values('Score_satisfaction',ascending =False)
print(df_clean_perf_conseillers)

             Nb_contrats  Prime_moy  Score_satisfaction  Nb_sinistres  \
conseiller
Leroy                126    1602.61                5.87           341
Moreau               119    1552.29                5.71           323
Martin               105    1527.69                5.63           250
Bernard              118    1698.46                5.48           283
Dubois               124    1514.36                5.43           316
Non assigné           16    1198.77                 NaN            47

             Taux_resiliation_%
conseiller
Leroy                      25.4
Moreau                     24.4
Martin                     28.6
Bernard                    22.0
Dubois                     18.5
Non assigné                31.2